experiments:
  mobilenetv2_finetune:
    architecture: MobileNetV2
    fine_tune_at: 120
    learning_rate: 0.0001
  resnet50:
    architecture: ResNet50
    learning_rate: 0.001
  efficientnetb0:
    architecture: EfficientNetB0
    learning_rate: 0.001

